# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: Clever Biscuit
description: Website for Clever Biscuit
url: http://cleverbiscuit.com

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: .tmp/src
destination: .tmp/dist
exclude: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
# NOTE: Don't use @ in front of your Twitter username
author:
  name: Mitchell Renton
  email: mitchrenton@gmail.com
  uri: www.mitchellrenton.com
  bio: UX Designer
  twitter:
  github: cleverbiscuit

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true
# Disables the more accurate related posts for faster generating of the site
lsi: false
# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
permalink: pretty
paginate: 10
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library and options
markdown: redcarpet
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true

# Move pages directory
include: ['_pages']

# Extending Jekyll
gems:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  projects:
    output: true